### PR TITLE
#400 BigCalendar styling

### PR DESCRIPTION
**Pull request by MichaelLonin**

### CODE REVIEW

**Comment by alxmiron** [comment]
why did you create a fork of our fork?) I pushed changes to feature/400 in HiTask/react-big-calendar repo. You can work there (when issue & MR are assigned to you) and create PR to master branch, inside single repository

**Comment by alxmiron** [comment]
if you need access to push to Hitask/react-big-calendar, notify me

**Comment by alxmiron** [comment]
your changes were modified in `feature/400-2` and merged to master

**Comment by MichaelLonin** [comment]
1. Next time will work inside HiTask/react-big-calendar repo
2. if you need access to push to Hitask/react-big-calendar, notify me. Sure!

**Pull request closed without merging**
